route:
  group_by: ['alertname', 'job']
  group_interval: 20s
  repeat_interval: 20s
  group_wait: 2s
  receiver: 'prometheus-rubberband'

receivers:
- name: 'prometheus-rubberband'
  webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
  - send_resolved: true

